spring:
  application:
    name: microservice-checkout
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance: hostname

server:
  port: 9090


