spring:
  application:
    name: microservice-checkout
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: microservice-config
    loadBalancer:
      configurations: weighted
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost

server:
  port: 9090

resilience4j:
  circuitbreaker:
    instances:
      product:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5  # Asegura que evalúe después de 5 llamadas
        failureRateThreshold: 50 # 50% de fallos activa el CB
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true





