spring:
  application:
    name: microservice-checkout
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: microservice-config
    loadBalancer:
      configurations: weighted
  config:
    import: "optional:configserver:"

eureka:
  instance:
    hostname: localhost

server:
  port: 9090







